export const usersData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    message: "Hello, I am interested in your services.",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    message: "Can you provide more details about your product?",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    message: "I have a question regarding your pricing.",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice.brown@example.com",
    message: "Is there any discount for bulk orders?",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    message: "I need support with my account.",
  },
  {
    id: 6,
    name: "Emily Clark",
    email: "emily.clark@example.com",
    message: "What is your refund policy?",
  },
  {
    id: 7,
    name: "Frank Miller",
    email: "frank.miller@example.com",
    message: "Can I change my subscription plan?",
  },
  {
    id: 8,
    name: "Grace Wilson",
    email: "grace.wilson@example.com",
    message: "How do I reset my password?",
  },
  {
    id: 9,
    name: "Hank Moore",
    email: "hank.moore@example.com",
    message: "Can you assist me with a technical issue?",
  },
  {
    id: 10,
    name: "Ivy Taylor",
    email: "ivy.taylor@example.com",
    message: "Do you offer a free trial?",
  },
  {
    id: 11,
    name: "Jack Anderson",
    email: "jack.anderson@example.com",
    message: "I have feedback about your service.",
  },
  {
    id: 12,
    name: "Kathy Harris",
    email: "kathy.harris@example.com",
    message: "Can I upgrade my plan mid-cycle?",
  },
  {
    id: 13,
    name: "Leo Martin",
    email: "leo.martin@example.com",
    message: "I have an issue with my billing.",
  },
  {
    id: 14,
    name: "Mia Thompson",
    email: "mia.thompson@example.com",
    message: "Do you have an affiliate program?",
  },
  {
    id: 15,
    name: "Noah White",
    email: "noah.white@example.com",
    message: "I need help with my account settings.",
  },
  {
    id: 16,
    name: "Olivia Walker",
    email: "olivia.walker@example.com",
    message: "Can you explain your features?",
  },
  {
    id: 17,
    name: "Paul Hall",
    email: "paul.hall@example.com",
    message: "I am experiencing slow performance.",
  },
  {
    id: 18,
    name: "Quincy Lee",
    email: "quincy.lee@example.com",
    message: "Is there a mobile app available?",
  },
  {
    id: 19,
    name: "Rachel Scott",
    email: "rachel.scott@example.com",
    message: "Can you provide a demo?",
  },
  {
    id: 20,
    name: "Steve Turner",
    email: "steve.turner@example.com",
    message: "How do I cancel my subscription?",
  },
];
